# Generated by Django 3.2.4 on 2021-06-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchresult',
            name='searchresult_unique',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='user',
        ),
    ]
