# Generated by Django 3.1.2 on 2021-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_video'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('url', 'user'), name='myvideo_unique'),
        ),
    ]
